
<style type="text/css">
    body {

        font-family: "Source Code Pro", "Consolas", "Monaco", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace;
        font-size: 11px;
    }

    .bullet {
        padding: 7px 0;
    }
    ul {
        list-style: none;
        display: table;
    }
    li {

        list-style-type: none;
    }

    li span {

        font-family: "Source Code Pro", "Consolas", "Monaco", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace;
        font-size: 11px;
        display: table-cell;
        padding: 5px;
    }


    .fa {
        display: table-cell;
        padding: 2px;
        text-align: center;
    }
    .fa-check{
        color: green;
    }
    .fa-warning{
        color: #ffb039;
    }
    .fa-close{
        color: red;
    }
    .fa-info-circle{
        color: #64ccff;
    }

    .header{
        font-weight: 700;
        font-size: 13px;
    }

    pre {outline: 1px solid #ccc; padding: 5px; margin: 5px; }
    .string { color: green; }
    .number { color: darkorange; }
    .boolean { color: blue; }
    .null { color: magenta; }
    .key { color: red; }
</style>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

