tmp: ./tmp

app: src
dest: dist

lodash:
  buildType: underscore
  include: omit,pick,values,keys,where
  exports: none
  dest: lodash/lo.js





output:
  modules:
    jquery: core, selector, events, ajaxx
    radic: widgets, waterfall, lodash