tmp: ./tmp

app: src
dest: dist

# - jQuery modules: core, selector,  traversing, callbacks,  deferred, core/ready, data,  queue, queue/delay,
#                 attributes,  event, event/alias, manipulation,  manipulation/_evalUrl, wrap,  css, css/hiddenVisibleSelectors,
#                 serialize,  ajax, ajax/xhr, ajax/script, ajax/jsonp, ajax/load, effects,  effects/animatedSelector, offset,  dimensions, deprecated,  exports/amd, exports/global"
# core and selector are mandatory
# -Radic modules: async, cookie, crypt, etag, github, github-extra, lodash, lotemplates, sprintf, widgets

build:
  filename: jquery.custom
  modules:
    jquery: core, selector, traversing, event, ajax
    radic: github, async, lodash, lotemplates


# Some file sizes as example: (remember, gzip/deflate makes it even smaller)
# default jquery-1.11.1.min.js = 93kb
#-------------------------------
#    jquery: core
#    radic: widgets
#    size: 12.8kb / 4.0kb (minified)
#-------------------------------
#    jquery: core
#    radic: github
#    size: 31kb / 14kb (minified)
#-------------------------------
#    jquery: core, selector, traversing, event, ajax
#    radic: github, async, lodash, lotemplates
#    size: 236kb / 64kb (minified)


